name = "signafi-market-worker"
main = "src/index.ts"
compatibility_date = "2026-04-30"

[vars]
DERIBIT_BASE_URL = "https://signafi-products.vercel.app/api/deribit"

[triggers]
crons = ["*/2 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "signafi_market"
database_id = "3e513c83-a26e-4b02-8785-881bbc8d8fb7"

[[durable_objects.bindings]]
name = "MARKET_DATA"
class_name = "MarketDataDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MarketDataDurableObject"]
